### ISSUE TITLE
Clean-up variable args in mixins

### ISSUE THREAD

**Issue by jrah** [madbitco/madsauce#1]
What is the reason for the argument to be in quotes (see: https://github.com/madbitco/madsauce/blob/master/css/_typography.scss#L59:L70) ? Is this a mistake, or do they need to be unquoted later? I am going to remove the quotes in the CSS class on my fork for now.

Example:
```css
.va-textbottom {
    vertical-align: "text-bottom";
}
```

Ref:  
https://github.com/madbitco/madsauce/blob/master/css/_typography.scss#L59:L70

/cc @matthewmorek
